config/routes.rb
StonepathExample::Application.routes.draw do
  devise_for :users

  authenticated :user, lambda {|u| u.role.reporter? } do
    root to: "issues#index", as: 'reporter_root'
  end

  authenticated :user, lambda {|u| u.role.deployer? } do
    root to: "issues#list_unscheduled", as: 'deployer_root'
  end

  authenticated :user, lambda {|u| u.role.developer? } do
    root to: "issues#list_assigned", as: 'developer_root'
  end

  devise_scope :user do
    root to: "devise/sessions#new", as: 'login_root'
  end

  resources :issues, only: [:index, :new, :create, :show] do
    resources :comments, only: [:create]
    member do
      post 'claim'
      post 'schedule_deployment'
      post 'sign_off'
    end
    collection do
      get 'list_pending'
      get 'list_assigned'
      get 'list_unscheduled'
    end
  end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :issue
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  include StonePath::WorkItem

  validates :title, presence: true, allow_nil: false
  validates :description, presence: true, allow_nil: false

  belongs_to :developer, class_name: 'User'
  has_many :comments
  owned_by :user
  tasked_through :task

  state_machine do
    state :pending, initial: true,
      after_enter: [:create_claim_task, :create_deploy_task],
      after_exit: :destroy_claim_task
    state :in_progress, after_enter: :create_develop_task,
      after_exit: :destroy_develop_task
    state :closed, after_enter: :destroy_deploy_task

    event :claim do
      transitions from: :pending, to: :in_progress
    end

    event :timeout do
      transitions from: :in_progress, to: :pending
    end

    event :close do
      transitions from: :in_progress, to: :closed, guard: :completed?
    end
  end

  ### scopes ###

  scope :open, -> { where("aasm_state <> 'closed'") }
  scope :pending, -> { where("aasm_state = 'pending'") }
  scope :unscheduled, -> { where(deployment_date: nil) }

  def self.assigned_to_developer(user)
    open.where(developer: user)
  end

  ### entry / exit actions ###

  def create_claim_task
    Task.create(workbench: Role.developer, workitem: self)
  end

  def destroy_claim_task
    Task.find_assignment(workbench: Role.developer, workitem: self).destroy
  end

  def create_deploy_task
    Task.create(workbench: Role.deployer, workitem: self)
  end

  def destroy_deploy_task
    Task.find_assignment(workbench: Role.deployer, workitem: self).destroy
  end

  def create_develop_task
    deadline = DateTime.now + 5.minutes
    Task.create(workbench: developer, workitem: self, due_at: deadline)
  end

  def destroy_develop_task
    Task.find_assignment(workbench: developer, workitem: self).destroy
  end

  def completed?
    signed_off and deployment_date.present?
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users

  def self.developer
    Role.get('developer')
  end

  def self.deployer
    Role.get('deployer')
  end

  def self.reporter
    Role.get('reporter')
  end

  def developer?
    name == 'developer'
  end

  def deployer?
    name == 'deployer'
  end

  def reporter?
    name == 'reporter'
  end

  private

  def self.get(name)
    Role.where(name: name).take
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  include StonePath::SPTask

  state_machine do
    state :active, initial: true, after_enter: :notify_created
    state :completed, enter: :timestamp_complete, after_enter: :notify_closed

    state :expired, after_enter: :notify_closed
    state :cancelled, after_enter: :notify_closed

    event :complete do
      transitions from: :active, to: :completed
    end

    event :cancel do
      transitions from: [:active, :completed], to: :cancelled
    end

    event :expire do
      transitions from: :active, to: :expired
    end
  end

  scope :unassigned, -> { where('workbench_id IS NULL') }
  scope :assigned, -> { where('workbench_id IS NOT NULL') }
  scope :active, -> { where('aasm_state in (?)', ['active']) }
  scope :completed, -> { where('aasm_state in (?)', ['completed']) }
  scope :expired, -> { where('aasm_state in (?)', ['expired']) }
  scope :cancelled, -> { where('aasm_state in (?)', ['cancelled']) }
  scope :overdue, -> { where('aasm_state in (?) AND due_at < ?', ['active'], Time.now) }

  def overdue?
    (Time.now > due_at) && self.active?
  end

  def self.find_assignment(workbench: nil, workitem: nil)
    Task.where(
      workbench_id: workbench.id,
      workbench_type: workbench.class.name,
      workitem_id: workitem.id,
      workitem_type: workitem.class.name,
    ).take
  end

  private

  def timestamp_complete
    self.completed_at = Time.now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  # TODO: Start using Cancan instead.
  def require_role(role_name)
    unless current_user.role.name == role_name
      flash[:error] = 'Access denied'
      redirect_to '/'
      return false
    end
    true
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :role_id
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @issue = Issue.find(params[:issue_id])
    @comment = @issue.comments.new(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to @issue
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :authenticate_user!

  def index
    require_role 'reporter' or return
    @issues = Issue.open
  end

  def list_unscheduled
    require_role 'deployer' or return
    @issues = Issue.unscheduled
    render 'index'
  end

  def list_assigned
    require_role 'developer' or return
    @issues = Issue.assigned_to_developer(current_user)
    render 'index'
  end

  def list_pending
    require_role 'developer' or return
    @issues = Issue.pending
    render 'index'
  end

  def new
    require_role 'reporter' or return
    @issue = Issue.new
  end

  def create
    require_role 'reporter' or return
    @issue = Issue.new(issue_params)
    @issue.owner = current_user

    if @issue.save
      redirect_to @issue
    else
      render 'new'
    end
  end

  def show
    @issue = find_issue
  end

  def claim
    require_role 'developer' or return
    @issue = find_issue
    @issue.developer = current_user
    @issue.claim! # _attempt_ to close the issue
    redirect_to @issue
  end

  def sign_off
    require_role 'developer' or return
    @issue = find_issue
    @issue.signed_off = true
    @issue.close!
    redirect_to @issue
  end

  def schedule_deployment
    require_role 'deployer' or return
    @issue = find_issue
    @issue.assign_attributes(deployment_schedule_params)

    if @issue.valid?
      @issue.save!
      @issue.close!
      redirect_to @issue
    else
      render 'show'
    end
  end

  private

  def find_issue
    Issue.find(params[:id])
  end

  def issue_params
    params.require(:issue).permit(:title, :description)
  end

  def deployment_schedule_params
    params.require(:issue).permit(:deployment_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_class_for_controller(*controller)
    is_active = controller.include?(params[:controller])
    is_active ? "active" : ""
  end

  def current_user_in_role(role_name)\
    return false if current_user.nil?
    current_user.role.name == role_name.to_s
  end
end

app/views/comments/_comment.html.erb
<div class="comment row">
  <div class="col-md-2 comment-commenter">
    <%= comment.user.email %>
  </div>
  <div class="col-md-10 comment-content">
    <%= simple_format comment.comment, wrapper_tag: 'div' %>
  </div>
</div>

app/views/issues/index.html.erb
<% content_for :banner do %>
  View Issues
<% end %>

<table class="table table-striped">
  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.id %></td>
        <td><%= link_to issue.title, issue %></td>
        <td><%= issue.deployment_date %></td>
        <td><%= issue.signed_off %></td>
      </tr>
    <% end %>
  </tbody>
  <thead>
    <tr>
      <th>Number</th>
      <th>Title</th>
      <th>Deployment Date</th>
      <th>Signed Off</th>
    </tr>
  </thead>
</table>

app/views/issues/new.html.erb
<% content_for :banner do %>
  Create an Issue
<% end %>

<%= simple_form_for @issue, class: 'form-horizontal' do |f| %>
  <%= f.input :title, label: 'Issue Title', required: true %>
  <%= f.input :description, required: true %>
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <%= f.button :submit, class: 'btn btn-success' %>
      <%= link_to 'Cancel', :back, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/issues/show.html.erb
<% content_for :banner do %>
  <%= @issue.title %>

  <% if current_user_in_role(:developer) && @issue.aasm_state == 'pending' %>
    <%= button_to 'Claim Issue', claim_issue_path(@issue),
        class: 'btn btn-primary pull-right' %>
  <% elsif current_user == @issue.developer %>
    <%= button_to 'Sign Off', sign_off_issue_path(@issue),
        class: 'btn btn-primary pull-right' %>
  <% end %>
<% end %>

<div class="form-horizontal">
  <%= render partial: 'shared/field', locals: {
        label: 'Reporter',
        content: @issue.owner.nil? ? 'None' : @issue.owner.email
      }
   %>
  <%= render partial: 'shared/field', locals: {
        label: 'Developer',
        content: @issue.developer.nil? ? 'None' : @issue.developer.email
      }
   %>
  <div class="form-group">
    <label class="control-label col-md-2">Deployment Date</label>
    <div class="col-md-10">
      <% if current_user_in_role(:deployer) %>
        <%= form_for @issue,
            url: {action: "schedule_deployment"},
            html: {method: 'post'} do |f| %>
          <%= f.date_select :deployment_date, {},
              {class: 'date form-control'} %>
          <%= f.button 'Schedule Deployment', class: 'btn btn-success' %>
        <% end %>
      <% else %>
        <p class="form-control-static">
          <%= @issue.deployment_date.nil? ? 'None' : @issue.deployment_date %>
        </p>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-2">Description</label>
    <div class="col-md-10">
      <%= simple_format @issue.description,
          {class: 'form-control-static'},
          wrapper_tag: 'div' %>
    </div>
  </div>
</div>

<div class="spacer"></div>

<h2>Comments</h2>
<%= render @issue.comments %>

<%= simple_form_for [@issue, @issue.comments.build], class: 'form-horizontal' do |f| %>
  <%= f.input :comment, label: 'New Comment', required: true %>
  <div class="row">
    <div class="col-md-10 col-md-offset-2">
      <%= f.button :submit, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tissue Tracker</title>
    <%= stylesheet_link_tag "application", media: "all",
        "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle"
                data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <% if current_user_in_role(:reporter) %>
            <li class="<%= nav_class_for_controller('work_logs') %>">
              <%= link_to 'Create an Issue', new_issue_path %>
            </li>
            <li class="<%= nav_class_for_controller('clients') %>">
              <%= link_to 'View Open Issues', issues_path %>
            </li>
          <% elsif current_user_in_role(:deployer) %>
            <li class="<%= nav_class_for_controller('work_logs') %>">
              <%= link_to 'View Unscheduled Issues', list_unscheduled_issues_path %>
            </li>
          <% elsif current_user_in_role(:developer) %>
            <li class="<%= nav_class_for_controller('work_logs') %>">
              <%= link_to 'View My Issues', list_assigned_issues_path %>
            </li>
            <li class="<%= nav_class_for_controller('clients') %>">
              <%= link_to 'View Pending Issues', list_pending_issues_path %>
            </li>
          <% end %>
        </ul>
        <% unless current_user.nil? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to current_user.email, edit_user_registration_path,
                  class: 'navbar-link' %>
            </li>
            <li>
              <%= link_to destroy_user_session_path,
                  method: :delete, class: 'navbar-link' do %>
                logout
                <span class="glyphicon glyphicon-log-out"></span>
              <% end %>
            </li>
          </div>
        <% end %>
      </div>
    </nav>

    <div class="flashes">
      <div class="no-margin-collapse">&nbsp;</div>
      <% flash.each do |name, message| %>
        <div class="alert alert-<%= name %>">
          <%= message %>
        </div>
      <% end %>
    </div>

    <div class="body">
      <div class="banner-header">
        <div class="banner">
          <h1><%= yield :banner %></h1>
          <div>
            <span class="corner-bottom corner-left"></span>
            <span class="corner-bottom corner-right"></span>
          </div>
        </div>
      </div>
      <div class="content">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_field.html.erb
<div class="form-group">
  <label class="control-label col-md-2"><%= label %></label>
  <div class="col-md-10">
    <p class="form-control-static"><%= content %></p>
  </div>
</div>